### ISSUE TITLE
[RuntimeError] shape mismatch

### ISSUE THREAD

**Issue by Romaosir** [thu-coai/ShieldLM#2]
你好，我在运行 sh infer_shieldlm.sh后报错

```Traceback (most recent call last):
  File "ShieldLM/infer_shieldlm.py", line 132, in <module>
    outputs = generate(datas, model, tokenizer, device, args.lang, args.model_base, args.batch_size, rules)
  File "ShieldLM/infer_shieldlm.py", line 89, in generate
    generation_output = model.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1313, in generate
    return super().generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1103, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 933, in forward
    outputs = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 634, in forward
    attn_outputs = self.attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 541, in forward
    context_layer = self.core_attention_flash(q, k, v, attention_mask=attention_mask)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 225, in forward
    output = self.pad_input(output, indices_k, batch_size, seqlen_q)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 170, in pad_input
    output[indices] = hidden_states
RuntimeError: shape mismatch: value tensor of shape [508, 40, 128] cannot be broadcast to indexing result of shape [466, 40, 128]
```

我的环境：
transformers==4.38.2
torch==2.2.0

我需要帮助，谢谢！

**Comment by nonstopfor** [comment]
有点奇怪，看库的版本感觉没什么问题，暂时没想到是什么原因。您那边如果跑原本的qwen模型有问题吗

**Comment by Romaosir** [comment]
> 有点奇怪，看库的版本感觉没什么问题，暂时没想到是什么原因。您那边如果跑原本的qwen模型有问题吗

跑通了，应该是transformers版本问题，谢谢

**Comment by Romaosir** [comment]
transformers版本换成了4.31.0，跑通
